- name: Docker
  uses: docker/setup-buildx-action@v1.0.0

name: ci

on:
  push:
    branches: master
  pull_request:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      -
        name: Build
        run: |
          docker build . # will run buildx